### ISSUE TITLE
잘못된 사이트 링크

### ISSUE THREAD

**Issue by rishubil** [devpools/devpools.github.io#1]
안녕하세요.
사이트에 사용된 URL 중 `www.devpool.kr`를 `www.devpools.kr`로 변경하셔야 할 것 같습니다.
예를 들면 RSS(ATOM) 구독을 위한 링크 등에 잘못된 URL이 사용되고 있습니다.

**Comment by ikaruce** [comment]
https://github.com/devpools/devpools.github.io/search?q=devpool.kr&unscoped_q=devpool.kr 결과를 확인해봐야할거 같아요.

**Comment by ehrudxo** [comment]
감사합니다. 처리했습니다.
